# Generated by Django 3.1.5 on 2021-02-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='area_hectares',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='justification',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
